### ISSUE TITLE
Tests fail withh sassc 2.2.1

### ISSUE THREAD

**Issue by dleidert** [jekyll/jekyll-sass-converter#103]
I was trying to package your latest release for the Debian system and ran into several test failures. So I cloned the git repository, installed the sassc 2.2.1 gem and ran the tests again. There are several issues. Especially some output does not match:

```
Failures:

  1) Jekyll::Converters::Sass in a site nested inside directory with square brackets produces CSS without raising errors
     Failure/Error: expect { site.process }.not_to raise_error

       expected no Exception, got #<Jekyll::Converters::Scss::SyntaxError: File to import not found or unreadable: grid. on line 1> with backtrace:
         # ./spec/sass_converter_spec.rb:112:in `block (4 levels) in <top (required)>'
         # ./spec/sass_converter_spec.rb:112:in `block (3 levels) in <top (required)>'
     # ./spec/sass_converter_spec.rb:112:in `block (3 levels) in <top (required)>'

  2) Jekyll::Converters::Sass converting sass includes the syntax error line in the syntax error message
     Failure/Error:
       expect do
         converter.convert(invalid_content)
       end.to raise_error(Jekyll::Converters::Scss::SyntaxError, error_message)

       expected Jekyll::Converters::Scss::SyntaxError with message matching /\AError: Invalid CSS after "f": expected 1 selector or at-rule. was "font-family: \$font-"\s+on line 1:1 of stdin/, got #<Jekyll::Converters::Scss::SyntaxError: Invalid CSS after "$font-stack": expected expression (e.g. 1px, bold), was ";" on line 1> with backtrace:
         # ./spec/sass_converter_spec.rb:58:in `block (4 levels) in <top (required)>'
         # ./spec/sass_converter_spec.rb:57:in `block (3 levels) in <top (required)>'
     # ./spec/sass_converter_spec.rb:57:in `block (3 levels) in <top (required)>'

  3) Jekyll::Converters::Sass converting sass produces CSS
     Failure/Error: expect(converter.convert(content)).to eql(css_output)

       expected: "body { font-family: Helvetica, sans-serif; font-color: fuschia; }\n"
            got: "body {\n  font-family: Helvetica, sans-serif;\n  font-color: fuschia; }\n"

       (compared using eql?)

       Diff:
       @@ -1,2 +1,4 @@
       -body { font-family: Helvetica, sans-serif; font-color: fuschia; }
       +body {
       +  font-family: Helvetica, sans-serif;
       +  font-color: fuschia; }
     # ./spec/sass_converter_spec.rb:51:in `block (3 levels) in <top (required)>'

  4) Jekyll::Converters::Scss importing from external libraries unsafe mode brings in the grid partial
     Failure/Error:
       expect(File.read(test_css_file)).to eql(
         "a { color: #999999; }\n\n/*# sourceMappingURL=main.css.map */"
       )

       expected: "a { color: #999999; }\n\n/*# sourceMappingURL=main.css.map */"
            got: "a {\n  color: #999999; }\n"

       (compared using eql?)

       Diff:
       @@ -1,4 +1,3 @@
       -a { color: #999999; }
       -
       -/*# sourceMappingURL=main.css.map */
       +a {
       +  color: #999999; }
     # ./spec/scss_converter_spec.rb:201:in `block (4 levels) in <top (required)>'

  5) Jekyll::Converters::Scss when building configurations when specifying sass dirs when the sass dir exists not allow sass_dirs outside of site source
     Failure/Error:
       expect(
         converter("sass_dir" => "/etc/passwd").sass_dir_relative_to_site_source
       ).to eql("etc/passwd")

       expected: "etc/passwd"
            got: "/tmp/jekyll-sass-converter/spec/source/etc/passwd"

       (compared using eql?)
     # ./spec/scss_converter_spec.rb:82:in `block (5 levels) in <top (required)>'

  6) Jekyll::Converters::Scss with valid sass paths in a theme in unsafe mode includes the theme's sass directory
     Failure/Error: expect(converter.sass_load_paths).to include(site.theme.sass_path)
       expected ["/tmp/jekyll-sass-converter/spec/source/_sass"] to include "/var/lib/gems/2.7.0/gems/minima-2.5.1/_sass"
     # ./spec/scss_converter_spec.rb:315:in `block (4 levels) in <top (required)>'

  7) Jekyll::Converters::Scss with valid sass paths in a theme in safe mode includes the theme's sass directory
     Failure/Error: expect(converter.sass_load_paths).to include(site.theme.sass_path)
       expected ["/tmp/jekyll-sass-converter/spec/source/_sass"] to include "/var/lib/gems/2.7.0/gems/minima-2.5.1/_sass"
     # ./spec/scss_converter_spec.rb:332:in `block (4 levels) in <top (required)>'

  8) Jekyll::Converters::Scss in a site nested inside directory with square brackets produces CSS without raising errors
     Failure/Error: expect { site.process }.not_to raise_error

       expected no Exception, got #<Jekyll::Converters::Scss::SyntaxError: File to import not found or unreadable: grid.
       Load paths:
         .../var/lib/gems/2.7.0/gems/minima-2.5.1/_sass
         /var/lib/gems/2.7.0/gems/minima-2.5.1/_sass on line 1> with backtrace:
         # ./spec/scss_converter_spec.rb:373:in `block (4 levels) in <top (required)>'
         # ./spec/scss_converter_spec.rb:373:in `block (3 levels) in <top (required)>'
     # ./spec/scss_converter_spec.rb:373:in `block (3 levels) in <top (required)>'

  9) Jekyll::Converters::Scss importing partials imports SCSS partial
     Failure/Error:
       expect(File.read(test_css_file)).to eql(
         ".half{width:50%}\n\n/*# sourceMappingURL=main.css.map */"
       )

       expected: ".half{width:50%}\n\n/*# sourceMappingURL=main.css.map */"
            got: ".half{width:50%}\n"

       (compared using eql?)

       Diff:
       @@ -1,4 +1,2 @@
        .half{width:50%}
       -
       -/*# sourceMappingURL=main.css.map */
     # ./spec/scss_converter_spec.rb:158:in `block (3 levels) in <top (required)>'

  10) Jekyll::Converters::Scss converting SCSS includes the syntax error line in the syntax error message
      Failure/Error:
        expect do
          converter.convert(invalid_content)
        end.to raise_error(Jekyll::Converters::Scss::SyntaxError, error_message)

        expected Jekyll::Converters::Scss::SyntaxError with message matching /\AError: Invalid CSS after "body": expected 1 selector or at-rule, was "{"\s+on line 2/, got #<Jekyll::Converters::Scss::SyntaxError: Invalid CSS after "body ": expected selector or at-rule, was "{" on line 2> with backtrace:
          # ./spec/scss_converter_spec.rb:131:in `block (4 levels) in <top (required)>'
          # ./spec/scss_converter_spec.rb:130:in `block (3 levels) in <top (required)>'
      # ./spec/scss_converter_spec.rb:130:in `block (3 levels) in <top (required)>'

  11) Jekyll::Converters::Scss converting SCSS produces CSS
      Failure/Error: expect(converter.convert(content)).to eql(css_output)

        expected: "body { font-family: Helvetica, sans-serif; font-color: fuschia; }\n"
             got: "body {\n  font-family: Helvetica, sans-serif;\n  font-color: fuschia; }\n"

        (compared using eql?)

        Diff:
        @@ -1,2 +1,4 @@
        -body { font-family: Helvetica, sans-serif; font-color: fuschia; }
        +body {
        +  font-family: Helvetica, sans-serif;
        +  font-color: fuschia; }
      # ./spec/scss_converter_spec.rb:124:in `block (3 levels) in <top (required)>'

Finished in 0.09174 seconds (files took 0.25403 seconds to load)
41 examples, 11 failures

Failed examples:

rspec ./spec/sass_converter_spec.rb:111 # Jekyll::Converters::Sass in a site nested inside directory with square brackets produces CSS without raising errors
rspec ./spec/sass_converter_spec.rb:54 # Jekyll::Converters::Sass converting sass includes the syntax error line in the syntax error message
rspec ./spec/sass_converter_spec.rb:50 # Jekyll::Converters::Sass converting sass produces CSS
rspec ./spec/scss_converter_spec.rb:199 # Jekyll::Converters::Scss importing from external libraries unsafe mode brings in the grid partial
rspec ./spec/scss_converter_spec.rb:81 # Jekyll::Converters::Scss when building configurations when specifying sass dirs when the sass dir exists not allow sass_dirs outside of site source
rspec ./spec/scss_converter_spec.rb:313 # Jekyll::Converters::Scss with valid sass paths in a theme in unsafe mode includes the theme's sass directory
rspec ./spec/scss_converter_spec.rb:329 # Jekyll::Converters::Scss with valid sass paths in a theme in safe mode includes the theme's sass directory
rspec ./spec/scss_converter_spec.rb:372 # Jekyll::Converters::Scss in a site nested inside directory with square brackets produces CSS without raising errors
rspec ./spec/scss_converter_spec.rb:157 # Jekyll::Converters::Scss importing partials imports SCSS partial
rspec ./spec/scss_converter_spec.rb:127 # Jekyll::Converters::Scss converting SCSS includes the syntax error line in the syntax error message
rspec ./spec/scss_converter_spec.rb:123 # Jekyll::Converters::Scss converting SCSS produces CSS
```

**Comment by dleidert** [comment]
If I install all gems using bundler into `vendor/bundle` the rspec tests succeed while sassc is at version 2.2.1 too. So this might actually be a downstream issue, not a bug :(

However I had to install sass too, which was not pulled in automatically. Otherwise these tests failed:

```
Failures:

  1) Jekyll::Converters::Scss with valid sass paths in a theme in safe mode includes the theme's sass directory
     Failure/Error:
       Jekyll::Site.new(
         site_configuration.merge(
           "theme" => "minima",
           "safe"  => true
         )
       )
     
     Jekyll::Errors::MissingDependencyException:
       sass
     # ./vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/external.rb:68:in `rescue in block in require_with_graceful_fail'
     # ./vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/external.rb:56:in `block in require_with_graceful_fail'
     # ./vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/external.rb:55:in `each'
     # ./vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/external.rb:55:in `require_with_graceful_fail'
     # ./vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/theme.rb:43:in `configure_sass'
     # ./vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/theme.rb:13:in `initialize'
     # ./vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/site.rb:439:in `new'
     # ./vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/site.rb:439:in `configure_theme'
     # ./vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/site.rb:55:in `config='
     # ./vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/site.rb:23:in `initialize'
     # ./spec/scss_converter_spec.rb:321:in `new'
     # ./spec/scss_converter_spec.rb:321:in `block (4 levels) in <top (required)>'
     # ./spec/scss_converter_spec.rb:330:in `block (4 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # LoadError:
     #   cannot load such file -- sass
     #   ./vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/external.rb:58:in `require'

  2) Jekyll::Converters::Scss with valid sass paths in a theme in unsafe mode includes the theme's sass directory
     Failure/Error:
       Jekyll::Site.new(
         site_configuration.merge("theme" => "minima")
       )
     
     Jekyll::Errors::MissingDependencyException:
       sass
     # ./vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/external.rb:68:in `rescue in block in require_with_graceful_fail'
     # ./vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/external.rb:56:in `block in require_with_graceful_fail'
     # ./vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/external.rb:55:in `each'
     # ./vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/external.rb:55:in `require_with_graceful_fail'
     # ./vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/theme.rb:43:in `configure_sass'
     # ./vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/theme.rb:13:in `initialize'
     # ./vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/site.rb:439:in `new'
     # ./vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/site.rb:439:in `configure_theme'
     # ./vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/site.rb:55:in `config='
     # ./vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/site.rb:23:in `initialize'
     # ./spec/scss_converter_spec.rb:308:in `new'
     # ./spec/scss_converter_spec.rb:308:in `block (4 levels) in <top (required)>'
     # ./spec/scss_converter_spec.rb:314:in `block (4 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # LoadError:
     #   cannot load such file -- sass
     #   ./vendor/bundle/ruby/2.7.0/gems/jekyll-3.8.6/lib/jekyll/external.rb:58:in `require'

Finished in 0.09335 seconds (files took 0.22639 seconds to load)
41 examples, 2 failures
```

**Comment by ashmaroli** [comment]
Hello again @dleidert 
Yes there are differences between output generated by `sass` and `sassc` gems. We took this into consideration and bumped the major version of this plugin.

So the summary is:
- Jekyll 3.x uses jekyll-sass-converter-1.x and older.
- Jekyll 4.x uses jekyll-sass-converter-2.x.
- jekyll-sass-converter-2.x uses only `sassc`. `sass` has been dropped.
- jekyll-sass-converter-2.x doesn't need `sass`, if there were tests that depended on its output, they have been removed.
- The latest Travis CI build (latest commit as of this writing) was a success and can be viewed here:
https://travis-ci.org/github/jekyll/jekyll-sass-converter/jobs/663709775

**Comment by dleidert** [comment]
@ashmaroli. Thanks for the reply. I hope you are not frustrated. We are running all gem tests and often reveal bugs as well. Sometimes there are false positives though which are more likely to be downstream related issues.

**Comment by ashmaroli** [comment]
No @dleidert I'm not frustrated.
Its a good thing that you package our software for additional distribution and conduct your own tests as well.
But you should also be mindful of the current state of the repository and its adoption of the semver principles. If tests prior to semver major version bump fails with the current repository state, it is most likely that those tests are no longer valid.

**Comment by dleidert** [comment]
I just checked jekyll-sass-converter's Gemfile/gemspec and it requires Jekyll >= 3. Version 4 is only set in travis builds, no? That's why I assumed jekyll 3 is still ok. (Yes, I didn't check jekyll at that time, which clearly requires version 1.x of this plugin.)

**Comment by ashmaroli** [comment]
Hmm.. You're right. The Gemfile should've been updated after Jekyll 4.0 shipped..
Thanks for bringing that to my notice.
