### ISSUE TITLE
Jekyll build failure with jekyll-sass-converter v3.0.0 on jekyll/jekyll docker image

### ISSUE THREAD

**Issue by gionn** [jekyll/jekyll-sass-converter#161]
Hello,

this is what I get if I try to build my [blog](https://github.com/gionn/blog) without pinning `jekyll-sass-converter` to 2.2.0

```
$ docker run --volume="$PWD:/srv/jekyll:Z" jekyll/jekyll jekyll build
Digest: sha256:400b8d1569f118bca8a3a09a25f32803b00a55d1ea241feaf5f904d66ca9c625
Bundler 2.3.25 is running, but your lockfile was generated with 2.3.7. Installing Bundler 2.3.7 and restarting using that version.
Fetching gem metadata from https://rubygems.org/.
Fetching bundler 2.3.7
Installing bundler 2.3.7
Fetching gem metadata from https://rubygems.org/.........
Fetching rake 13.1.0
Installing rake 13.1.0
Fetching bigdecimal 3.1.5
Fetching base64 0.2.0
Installing base64 0.2.0
Fetching concurrent-ruby 1.2.2
Installing bigdecimal 3.1.5 with native extensions
Installing concurrent-ruby 1.2.2
Fetching connection_pool 2.4.1
Installing connection_pool 2.4.1
Using ruby2_keywords 0.0.5
Fetching minitest 5.20.0
Installing minitest 5.20.0
Fetching mutex_m 0.2.0
Installing mutex_m 0.2.0
Fetching public_suffix 5.0.4
Installing public_suffix 5.0.4
Using bundler 2.3.7
Using colorator 1.1.0
Fetching cssminify2 2.0.1
Installing cssminify2 2.0.1
Using eventmachine 1.2.7
Using http_parser.rb 0.8.0
Fetching execjs 2.9.1
Installing execjs 2.9.1
Fetching faraday-net_http 3.0.2
Installing faraday-net_http 3.0.2
Fetching ffi 1.16.3
Installing ffi 1.16.3 with native extensions
Using forwardable-extended 2.6.0
Fetching gemoji 4.1.0
Fetching google-protobuf 3.25.1 (x86_64-linux)
Installing gemoji 4.1.0
Fetching mini_portile2 2.8.5
Installing mini_portile2 2.8.5
Fetching racc 1.7.3
Installing google-protobuf 3.25.1 (x86_64-linux)
Fetching htmlcompressor 0.4.0
Installing htmlcompressor 0.4.0
Using rb-fsevent 0.11.2
Fetching rexml 3.2.6
Installing racc 1.7.3 with native extensions
Installing rexml 3.2.6
Fetching liquid 4.0.4
Installing liquid 4.0.4
Using mercenary 0.4.0
Fetching rouge 4.2.0
Installing rouge 4.2.0
Using safe_yaml 1.0.5
Fetching unicode-display_width 2.5.0
Fetching webrick 1.8.1
Installing unicode-display_width 2.5.0
Fetching posix-spawn 0.3.15
Installing webrick 1.8.1
Fetching json 2.7.1
Installing posix-spawn 0.3.15 with native extensions
Installing json 2.7.1 with native extensions
Using jekyll-paginate 1.1.0
Fetching i18n 1.14.1
Installing i18n 1.14.1
Fetching tzinfo 2.0.6
Installing tzinfo 2.0.6
Fetching drb 2.2.0
Installing drb 2.2.0
Fetching addressable 2.8.6
Installing addressable 2.8.6
Using em-websocket 0.5.3
Fetching uglifier 4.2.0
Installing uglifier 4.2.0
Fetching faraday 2.8.1
Installing faraday 2.8.1
Using pathutil 0.16.2
Using rb-inotify 0.10.1
Fetching sass-embedded 1.69.5 (x86_64-linux-musl)
Installing sass-embedded 1.69.5 (x86_64-linux-musl)
Using kramdown 2.4.0
Fetching nokogiri 1.16.0 (x86_64-linux)
Installing nokogiri 1.16.0 (x86_64-linux)
Fetching terminal-table 3.0.2
Fetching activesupport 7.1.2
Installing terminal-table 3.0.2
Fetching sawyer 0.9.2
Installing activesupport 7.1.2
Installing sawyer 0.9.2
Fetching listen 3.8.0
Fetching jekyll-sass-converter 3.0.0
Installing listen 3.8.0
Using kramdown-parser-gfm 1.1.0
Fetching json-minify 0.0.3
Installing json-minify 0.0.3
Installing jekyll-sass-converter 3.0.0
Fetching octokit 4.25.1
Using html-pipeline 2.14.3
Using jekyll-watch 2.2.1
Fetching jekyll 4.3.3
Installing octokit 4.25.1
Fetching jekyll-gist 1.5.0
Installing jekyll 4.3.3
Using jekyll-feed 0.17.0
Fetching jekyll-last-modified-at 1.3.0
Installing jekyll-last-modified-at 1.3.0
Fetching jekyll-minifier 0.1.10
Installing jekyll-gist 1.5.0
Using jekyll-redirect-from 0.16.0
Using jekyll-seo-tag 2.8.0
Using jekyll-sitemap 1.4.0
Fetching jemoji 0.13.0
Installing jemoji 0.13.0
Fetching jekyll-theme-hydeout 4.2.0
Installing jekyll-minifier 0.1.10
Installing jekyll-theme-hydeout 4.2.0
Bundle complete! 9 Gemfile dependencies, 66 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-linux-musl]
Configuration file: /srv/jekyll/_config.yml
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':
                    end of file reached
                    ------------------------------------------------
      Jekyll 4.3.3   Please append `--trace` to the `build` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
/usr/gem/gems/sass-embedded-1.69.5-x86_64-linux-musl/lib/sass/embedded/varint.rb:20:in `readbyte': end of file reached (EOFError)
        from /usr/gem/gems/sass-embedded-1.69.5-x86_64-linux-musl/lib/sass/embedded/varint.rb:20:in `block in read'
        from /usr/gem/gems/sass-embedded-1.69.5-x86_64-linux-musl/lib/sass/embedded/varint.rb:19:in `loop'
        from /usr/gem/gems/sass-embedded-1.69.5-x86_64-linux-musl/lib/sass/embedded/varint.rb:19:in `read'
        from /usr/gem/gems/sass-embedded-1.69.5-x86_64-linux-musl/lib/sass/embedded/connection.rb:29:in `block (2 levels) in initialize'
        from /usr/gem/gems/sass-embedded-1.69.5-x86_64-linux-musl/lib/sass/embedded/connection.rb:28:in `loop'
        from /usr/gem/gems/sass-embedded-1.69.5-x86_64-linux-musl/lib/sass/embedded/connection.rb:28:in `block in initialize'
```

**Comment by ntkme** [comment]
That docker image is outdated. See https://github.com/envygeeks/jekyll-docker/issues. The maintainer of the image has not responded at all so we cannot do anything about it.

**Comment by gionn** [comment]
thanks for pointing out, I was wrongly assuming it was sort of official docker image.

Looks like a good alternative could be `timbru31/ruby-node:3.2`.

Thanks!
