### ISSUE TITLE
jekyll -v `check_for_activated_spec!': You have already activated jekyll-sass-converter 2.2.0,

### ISSUE THREAD

**Issue by locitran** [jekyll/jekyll-sass-converter#163]
I install ruby and other stuff inside a Docker container.

Everything works fine except for jekyll.

This command does not work even I can execute the site `bundle exec jekyll`
```
root@53a051cc01fc:/mnt/Tsunami_HHD/newloci/NativeEnsembleWeb_copy/gitpages/loci# jekyll -v
/root/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/runtime.rb:309:in `check_for_activated_spec!': You have already activated jekyll-sass-converter 2.2.0, but your Gemfile requires jekyll-sass-converter 1.5.2. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
        from /root/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/runtime.rb:25:in `block in setup'
        from /root/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/spec_set.rb:136:in `each'
        from /root/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/spec_set.rb:136:in `each'
        from /root/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/runtime.rb:24:in `map'
        from /root/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler/runtime.rb:24:in `setup'
        from /root/.rbenv/versions/3.1.2/lib/ruby/3.1.0/bundler.rb:151:in `setup'
        from /root/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/jekyll-4.3.4/lib/jekyll/plugin_manager.rb:52:in `require_from_bundler'
        from /root/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/jekyll-4.3.4/exe/jekyll:11:in `<top (required)>'
        from /root/.rbenv/versions/3.1.2/bin/jekyll:25:in `load'
        from /root/.rbenv/versions/3.1.2/bin/jekyll:25:in `<main>'
```

I have no idea how to fix it. Does it need to be fixed?

**Comment by ashmaroli** [comment]
The solution to the posted issue is to prepend `bundle exec` to the jekyll program.
Therefore, `bundle exec jekyll -v` should work as intended. If it doesn't, its probably because you haven't installed the correct version. (As per the above error, your gemfile needs Jekyll 3.x instead of more recent Jekyll 4.x).

So based on the given info, your solution is a two-step procedure:
1. Run `bundle install` inside the docker container.
2. Then run desired `jekyll` commands with `bundle exec` prepended:
    ```
    bundle exec jekyll --version
    ```
